FROM php:8.2-fpm-alpine3.19 AS build

RUN apk add php-session \
    php-tokenizer \
    php-xml \
    php-ctype \
    php-curl \
    php-dom \
    php-fileinfo \
    php-mbstring \
    php-openssl \
    php-pdo \
    php-pdo_mysql \
    php-session \
    php-tokenizer \
    php-xml \
    php-ctype \
    php-xmlwriter \
    php-simplexml \
    composer


RUN docker-php-ext-install mysqli pdo_mysql
RUN docker-php-ext-enable mysqli pdo_mysql

RUN apk add --update nodejs npm

COPY . /var/www/html

WORKDIR /var/www/html


RUN composer install
RUN npm install

EXPOSE 9000

RUN printf "\
chmod -R o+w /var/www/html/storage\n\
chown -R root:root /var/www/html/storage\n\
cp /usr/local/laravel.env /var/www/html/.env\n\
php-fpm\n\
" > /start.sh

RUN chmod +x "/start.sh"

ENTRYPOINT ["sh","/start.sh"]
